### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by ricardo777** [Unsigus/hass-homewizard-energy#1]
See attachments for missing icons:

![image](https://user-images.githubusercontent.com/1004317/97165330-d2d10380-1783-11eb-9289-d9a7c476ac3f.png)
![image](https://user-images.githubusercontent.com/1004317/97165449-fd22c100-1783-11eb-8d49-424a34c5092a.png)

Great that there is a start of a new plugin for Home Assistant,

**Comment by Unsigus** [comment]
I've added a logo, so it should show up in the main integration page. The search box logo will show up soon (submitted a PR to [home-assistant/brands](https://github.com/home-assistant/brands/pull/1997)

**Comment by Unsigus** [comment]
This component has now icons! Maybe it won't show up directly (caching) but everything seems fine now!
