### ISSUE TITLE
Do you want me to add GitHub Actions?

### ISSUE THREAD

**Issue by KTibow** [Unsigus/hass-homewizard-energy#2]
If you want, I can contribute some advanced CI to your repository in a PR. Let me know if you want that.

**Comment by Unsigus** [comment]
That would be awesome!

**Comment by KTibow** [comment]
Okay. Do you want to have HACS, hassfest, and flake8 separate or packaged together? I recommend packaged.

**Comment by Unsigus** [comment]
Packaged is fine!

**Comment by Unsigus** [comment]
That was quick! Thank you for your work
